apiVersion: apps/v1
kind: Deployment
metadata:
  name: chalupa-bot
  labels:
    app: chalupa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chalupa
  template:
    metadata:
      labels:
        app: chalupa
    spec:
      containers:
      - name: chalupa-bot
        image: ghcr.io/olivercodes/chalupa-bot:v0.0.1 # {"$imagepolicy": "flux-system:chalupa-bot-prod"}
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: DISCORD_TOKEN
